FROM jscdroiddev/jsc-dev-tools:latest

# Install netcore
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

ENV DOTNET_SDK_VERSION 3.1.201

RUN wget -q -O dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-musl-x64.tar.gz \
    && dotnet_sha512='9a8f14be881cacb29452300f39ee66f24e253e2df947f388ad2157114cd3f44eeeb88fae4e3dd1f9687ce47f27d43f2805f9f54694b8523dc9f998b59ae79996' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -C /usr/share/dotnet -xzf dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && rm dotnet.tar.gz
ENV DOTNET_USE_POLLING_FILE_WATCHER=true \ 
    NUGET_XMLDOC_MODE=skip

RUN dotnet help
RUN dotnet tool install --global dotnet-sonarscanner --version 4.8.0
RUN export PATH="${PATH}:/root/.dotnet/tools"

RUN rm -Rf /var/cache/apk
